import { Province, Region } from '@/types/region';

/**
 * 대한민국 16개 광역자치단체 및 세부 시·군·구 정적 행정구역 데이터
 * (2026년 7월 1일 출범한 '전남광주통합특별시' 행정체계 완벽 반영)
 * 
 * - 광주광역시 및 전라남도가 통합되어 '전남광주통합특별시' (27개 시·군·구) 하나로 통합 구성됨
 * - 좌표 출처: 대한민국 국토교통부 행정구역 주소정보 및 각 시·군·구청 대표 관측 좌표
 */
export const PROVINCES: Province[] = [
  {
    id: 'seoul',
    name: '서울특별시',
    regions: [
      { id: 'seoul-gangnam', sido: '서울특별시', sigungu: '강남구', displayName: '강남구', fullName: '서울특별시 강남구', latitude: 37.5172, longitude: 127.0473 },
      { id: 'seoul-gangdong', sido: '서울특별시', sigungu: '강동구', displayName: '강동구', fullName: '서울특별시 강동구', latitude: 37.5301, longitude: 127.1238 },
      { id: 'seoul-gangbuk', sido: '서울특별시', sigungu: '강북구', displayName: '강북구', fullName: '서울특별시 강북구', latitude: 37.6396, longitude: 127.0257 },
      { id: 'seoul-gangseo', sido: '서울특별시', sigungu: '강서구', displayName: '강서구', fullName: '서울특별시 강서구', latitude: 37.5509, longitude: 126.8495 },
      { id: 'seoul-gwanak', sido: '서울특별시', sigungu: '관악구', displayName: '관악구', fullName: '서울특별시 관악구', latitude: 37.4784, longitude: 126.9516 },
      { id: 'seoul-gwangjin', sido: '서울특별시', sigungu: '광진구', displayName: '광진구', fullName: '서울특별시 광진구', latitude: 37.5385, longitude: 127.0824 },
      { id: 'seoul-guro', sido: '서울특별시', sigungu: '구로구', displayName: '구로구', fullName: '서울특별시 구로구', latitude: 37.4954, longitude: 126.8874 },
      { id: 'seoul-geumcheon', sido: '서울특별시', sigungu: '금천구', displayName: '금천구', fullName: '서울특별시 금천구', latitude: 37.4568, longitude: 126.8955 },
      { id: 'seoul-nowon', sido: '서울특별시', sigungu: '노원구', displayName: '노원구', fullName: '서울특별시 노원구', latitude: 37.6542, longitude: 127.0568 },
      { id: 'seoul-dobong', sido: '서울특별시', sigungu: '도봉구', displayName: '도봉구', fullName: '서울특별시 도봉구', latitude: 37.6688, longitude: 127.0471 },
      { id: 'seoul-dongdaemun', sido: '서울특별시', sigungu: '동대문구', displayName: '동대문구', fullName: '서울특별시 동대문구', latitude: 37.5744, longitude: 127.04 },
      { id: 'seoul-dongjak', sido: '서울특별시', sigungu: '동작구', displayName: '동작구', fullName: '서울특별시 동작구', latitude: 37.5124, longitude: 126.9393 },
      { id: 'seoul-mapo', sido: '서울특별시', sigungu: '마포구', displayName: '마포구', fullName: '서울특별시 마포구', latitude: 37.5663, longitude: 126.9016 },
      { id: 'seoul-seodaemun', sido: '서울특별시', sigungu: '서대문구', displayName: '서대문구', fullName: '서울특별시 서대문구', latitude: 37.5791, longitude: 126.9368 },
      { id: 'seoul-seocho', sido: '서울특별시', sigungu: '서초구', displayName: '서초구', fullName: '서울특별시 서초구', latitude: 37.4837, longitude: 127.0324 },
      { id: 'seoul-seongdong', sido: '서울특별시', sigungu: '성동구', displayName: '성동구', fullName: '서울특별시 성동구', latitude: 37.5635, longitude: 127.0369 },
      { id: 'seoul-seongbuk', sido: '서울특별시', sigungu: '성북구', displayName: '성북구', fullName: '서울특별시 성북구', latitude: 37.5894, longitude: 127.0167 },
      { id: 'seoul-songpa', sido: '서울특별시', sigungu: '송파구', displayName: '송파구', fullName: '서울특별시 송파구', latitude: 37.5145, longitude: 127.1066 },
      { id: 'seoul-yangcheon', sido: '서울특별시', sigungu: '양천구', displayName: '양천구', fullName: '서울특별시 양천구', latitude: 37.5169, longitude: 126.8665 },
      { id: 'seoul-yeongdeungpo', sido: '서울특별시', sigungu: '영등포구', displayName: '영등포구', fullName: '서울특별시 영등포구', latitude: 37.5264, longitude: 126.8962 },
      { id: 'seoul-yongsan', sido: '서울특별시', sigungu: '용산구', displayName: '용산구', fullName: '서울특별시 용산구', latitude: 37.5326, longitude: 126.9906 },
      { id: 'seoul-eunpyeong', sido: '서울특별시', sigungu: '은평구', displayName: '은평구', fullName: '서울특별시 은평구', latitude: 37.6027, longitude: 126.9291 },
      { id: 'seoul-jongno', sido: '서울특별시', sigungu: '종로구', displayName: '종로구', fullName: '서울특별시 종로구', latitude: 37.5735, longitude: 126.979 },
      { id: 'seoul-junggu', sido: '서울특별시', sigungu: '중구', displayName: '중구', fullName: '서울특별시 중구', latitude: 37.5641, longitude: 126.9979 },
      { id: 'seoul-jungnang', sido: '서울특별시', sigungu: '중랑구', displayName: '중랑구', fullName: '서울특별시 중랑구', latitude: 37.6066, longitude: 127.0927 },
    ],
  },
  {
    id: 'busan',
    name: '부산광역시',
    regions: [
      { id: 'busan-haeundae', sido: '부산광역시', sigungu: '해운대구', displayName: '해운대구', fullName: '부산광역시 해운대구', latitude: 35.1631, longitude: 129.1636 },
      { id: 'busan-suyeong', sido: '부산광역시', sigungu: '수영구', displayName: '수영구', fullName: '부산광역시 수영구', latitude: 35.1456, longitude: 129.1132 },
      { id: 'busan-busanjin', sido: '부산광역시', sigungu: '부산진구', displayName: '부산진구', fullName: '부산광역시 부산진구', latitude: 35.163, longitude: 129.0532 },
      { id: 'busan-namgu', sido: '부산광역시', sigungu: '남구', displayName: '남구', fullName: '부산광역시 남구', latitude: 35.1365, longitude: 129.0844 },
      { id: 'busan-dongnae', sido: '부산광역시', sigungu: '동래구', displayName: '동래구', fullName: '부산광역시 동래구', latitude: 35.2048, longitude: 129.0776 },
      { id: 'busan-geumjeong', sido: '부산광역시', sigungu: '금정구', displayName: '금정구', fullName: '부산광역시 금정구', latitude: 35.243, longitude: 129.0921 },
      { id: 'busan-saha', sido: '부산광역시', sigungu: '사하구', displayName: '사하구', fullName: '부산광역시 사하구', latitude: 35.1044, longitude: 128.9749 },
      { id: 'busan-junggu', sido: '부산광역시', sigungu: '중구', displayName: '중구', fullName: '부산광역시 중구', latitude: 35.1062, longitude: 129.0324 },
      { id: 'busan-gangseo', sido: '부산광역시', sigungu: '강서구', displayName: '강서구', fullName: '부산광역시 강서구', latitude: 35.2122, longitude: 128.9806 },
      { id: 'busan-gijang', sido: '부산광역시', sigungu: '기장군', displayName: '기장군', fullName: '부산광역시 기장군', latitude: 35.2447, longitude: 129.2224 },
    ],
  },
  {
    id: 'daegu',
    name: '대구광역시',
    regions: [
      { id: 'daegu-suseong', sido: '대구광역시', sigungu: '수성구', displayName: '수성구', fullName: '대구광역시 수성구', latitude: 35.8581, longitude: 128.6308 },
      { id: 'daegu-junggu', sido: '대구광역시', sigungu: '중구', displayName: '중구', fullName: '대구광역시 중구', latitude: 35.8694, longitude: 128.6062 },
      { id: 'daegu-donggu', sido: '대구광역시', sigungu: '동구', displayName: '동구', fullName: '대구광역시 동구', latitude: 35.8865, longitude: 128.6355 },
      { id: 'daegu-seogu', sido: '대구광역시', sigungu: '서구', displayName: '서구', fullName: '대구광역시 서구', latitude: 35.8718, longitude: 128.5592 },
      { id: 'daegu-namgu', sido: '대구광역시', sigungu: '남구', displayName: '남구', fullName: '대구광역시 남구', latitude: 35.8462, longitude: 128.5976 },
      { id: 'daegu-bukgu', sido: '대구광역시', sigungu: '북구', displayName: '북구', fullName: '대구광역시 북구', latitude: 35.8962, longitude: 128.5898 },
      { id: 'daegu-dalseo', sido: '대구광역시', sigungu: '달서구', displayName: '달서구', fullName: '대구광역시 달서구', latitude: 35.8298, longitude: 128.5326 },
      { id: 'daegu-dalseong', sido: '대구광역시', sigungu: '달성군', displayName: '달성군', fullName: '대구광역시 달성군', latitude: 35.7745, longitude: 128.4314 },
    ],
  },
  {
    id: 'incheon',
    name: '인천광역시',
    regions: [
      { id: 'incheon-yeonsu', sido: '인천광역시', sigungu: '연수구', displayName: '연수구', fullName: '인천광역시 연수구', latitude: 37.4102, longitude: 126.6783 },
      { id: 'incheon-namdong', sido: '인천광역시', sigungu: '남동구', displayName: '남동구', fullName: '인천광역시 남동구', latitude: 37.4469, longitude: 126.7314 },
      { id: 'incheon-bupyeong', sido: '인천광역시', sigungu: '부평구', displayName: '부평구', fullName: '인천광역시 부평구', latitude: 37.507, longitude: 126.7218 },
      { id: 'incheon-seogu', sido: '인천광역시', sigungu: '서구', displayName: '서구', fullName: '인천광역시 서구', latitude: 37.5454, longitude: 126.676 },
      { id: 'incheon-junggu', sido: '인천광역시', sigungu: '중구', displayName: '중구', fullName: '인천광역시 중구', latitude: 37.4738, longitude: 126.6216 },
      { id: 'incheon-michuhol', sido: '인천광역시', sigungu: '미추홀구', displayName: '미추홀구', fullName: '인천광역시 미추홀구', latitude: 37.4635, longitude: 126.6503 },
      { id: 'incheon-gyeyang', sido: '인천광역시', sigungu: '계양구', displayName: '계양구', fullName: '인천광역시 계양구', latitude: 37.5374, longitude: 126.7377 },
      { id: 'incheon-ganghwa', sido: '인천광역시', sigungu: '강화군', displayName: '강화군', fullName: '인천광역시 강화군', latitude: 37.7465, longitude: 126.488 },
    ],
  },
  {
    id: 'daejeon',
    name: '대전광역시',
    regions: [
      { id: 'daejeon-yuseong', sido: '대전광역시', sigungu: '유성구', displayName: '유성구', fullName: '대전광역시 유성구', latitude: 36.3623, longitude: 127.3563 },
      { id: 'daejeon-seogu', sido: '대전광역시', sigungu: '서구', displayName: '서구', fullName: '대전광역시 서구', latitude: 36.3553, longitude: 127.3838 },
      { id: 'daejeon-junggu', sido: '대전광역시', sigungu: '중구', displayName: '중구', fullName: '대전광역시 중구', latitude: 36.3257, longitude: 127.4215 },
      { id: 'daejeon-donggu', sido: '대전광역시', sigungu: '동구', displayName: '동구', fullName: '대전광역시 동구', latitude: 36.3371, longitude: 127.4394 },
      { id: 'daejeon-daedeok', sido: '대전광역시', sigungu: '대덕구', displayName: '대덕구', fullName: '대전광역시 대덕구', latitude: 36.3607, longitude: 127.4197 },
    ],
  },
  {
    id: 'ulsan',
    name: '울산광역시',
    regions: [
      { id: 'ulsan-namgu', sido: '울산광역시', sigungu: '남구', displayName: '남구', fullName: '울산광역시 남구', latitude: 35.5438, longitude: 129.3301 },
      { id: 'ulsan-junggu', sido: '울산광역시', sigungu: '중구', displayName: '중구', fullName: '울산광역시 중구', latitude: 35.5696, longitude: 129.3328 },
      { id: 'ulsan-donggu', sido: '울산광역시', sigungu: '동구', displayName: '동구', fullName: '울산광역시 동구', latitude: 35.5049, longitude: 129.4166 },
      { id: 'ulsan-bukgu', sido: '울산광역시', sigungu: '북구', displayName: '북구', fullName: '울산광역시 북구', latitude: 35.5824, longitude: 129.3606 },
      { id: 'ulsan-ulju', sido: '울산광역시', sigungu: '울주군', displayName: '울주군', fullName: '울산광역시 울주군', latitude: 35.5226, longitude: 129.154 },
    ],
  },
  {
    id: 'sejong',
    name: '세종특별자치시',
    regions: [
      { id: 'sejong-sejong', sido: '세종특별자치시', sigungu: '세종시', displayName: '세종시', fullName: '세종특별자치시 세종시', latitude: 36.48, longitude: 127.289 },
    ],
  },
  {
    id: 'gyeonggi',
    name: '경기도',
    regions: [
      { id: 'gyeonggi-suwon', sido: '경기도', sigungu: '수원시', displayName: '수원시', fullName: '경기도 수원시', latitude: 37.2636, longitude: 127.0286 },
      { id: 'gyeonggi-seongnam', sido: '경기도', sigungu: '성남시', displayName: '성남시', fullName: '경기도 성남시', latitude: 37.42, longitude: 127.1265 },
      { id: 'gyeonggi-goyang', sido: '경기도', sigungu: '고양시', displayName: '고양시', fullName: '경기도 고양시', latitude: 37.6584, longitude: 126.832 },
      { id: 'gyeonggi-yongin', sido: '경기도', sigungu: '용인시', displayName: '용인시', fullName: '경기도 용인시', latitude: 37.2411, longitude: 127.1776 },
      { id: 'gyeonggi-bucheon', sido: '경기도', sigungu: '부천시', displayName: '부천시', fullName: '경기도 부천시', latitude: 37.5034, longitude: 126.766 },
      { id: 'gyeonggi-ansan', sido: '경기도', sigungu: '안산시', displayName: '안산시', fullName: '경기도 안산시', latitude: 37.3219, longitude: 126.8309 },
      { id: 'gyeonggi-hwaseong', sido: '경기도', sigungu: '화성시', displayName: '화성시', fullName: '경기도 화성시', latitude: 37.1995, longitude: 126.8315 },
      { id: 'gyeonggi-namyangju', sido: '경기도', sigungu: '남양주시', displayName: '남양주시', fullName: '경기도 남양주시', latitude: 37.636, longitude: 127.2165 },
      { id: 'gyeonggi-anyang', sido: '경기도', sigungu: '안양시', displayName: '안양시', fullName: '경기도 안양시', latitude: 37.3943, longitude: 126.9568 },
      { id: 'gyeonggi-pyeongtaek', sido: '경기도', sigungu: '평택시', displayName: '평택시', fullName: '경기도 평택시', latitude: 36.9921, longitude: 127.1129 },
      { id: 'gyeonggi-uijeongbu', sido: '경기도', sigungu: '의정부시', displayName: '의정부시', fullName: '경기도 의정부시', latitude: 37.7381, longitude: 127.0337 },
      { id: 'gyeonggi-paju', sido: '경기도', sigungu: '파주시', displayName: '파주시', fullName: '경기도 파주시', latitude: 37.7595, longitude: 126.7802 },
      { id: 'gyeonggi-siheung', sido: '경기도', sigungu: '시흥시', displayName: '시흥시', fullName: '경기도 시흥시', latitude: 37.3801, longitude: 126.8029 },
      { id: 'gyeonggi-gimpo', sido: '경기도', sigungu: '김포시', displayName: '김포시', fullName: '경기도 김포시', latitude: 37.6152, longitude: 126.7157 },
      { id: 'gyeonggi-gwangmyeong', sido: '경기도', sigungu: '광명시', displayName: '광명시', fullName: '경기도 광명시', latitude: 37.4786, longitude: 126.8647 },
      { id: 'gyeonggi-gwangju', sido: '경기도', sigungu: '광주시', displayName: '광주시', fullName: '경기도 광주시', latitude: 37.4089, longitude: 127.2566 },
      { id: 'gyeonggi-gunpo', sido: '경기도', sigungu: '군포시', displayName: '군포시', fullName: '경기도 군포시', latitude: 37.3614, longitude: 126.9352 },
      { id: 'gyeonggi-icheon', sido: '경기도', sigungu: '이천시', displayName: '이천시', fullName: '경기도 이천시', latitude: 37.2723, longitude: 127.4348 },
      { id: 'gyeonggi-osan', sido: '경기도', sigungu: '오산시', displayName: '오산시', fullName: '경기도 오산시', latitude: 37.1498, longitude: 127.0776 },
      { id: 'gyeonggi-hanam', sido: '경기도', sigungu: '하남시', displayName: '하남시', fullName: '경기도 하남시', latitude: 37.5393, longitude: 127.2148 },
      { id: 'gyeonggi-yangju', sido: '경기도', sigungu: '양주시', displayName: '양주시', fullName: '경기도 양주시', latitude: 37.7853, longitude: 127.0458 },
      { id: 'gyeonggi-guri', sido: '경기도', sigungu: '구리시', displayName: '구리시', fullName: '경기도 구리시', latitude: 37.5943, longitude: 127.1296 },
      { id: 'gyeonggi-anseong', sido: '경기도', sigungu: '안성시', displayName: '안성시', fullName: '경기도 안성시', latitude: 37.008, longitude: 127.2797 },
      { id: 'gyeonggi-pocheon', sido: '경기도', sigungu: '포천시', displayName: '포천시', fullName: '경기도 포천시', latitude: 37.8949, longitude: 127.2003 },
      { id: 'gyeonggi-uiwang', sido: '경기도', sigungu: '의왕시', displayName: '의왕시', fullName: '경기도 의왕시', latitude: 37.3448, longitude: 126.9682 },
      { id: 'gyeonggi-yeoju', sido: '경기도', sigungu: '여주시', displayName: '여주시', fullName: '경기도 여주시', latitude: 37.2982, longitude: 127.637 },
      { id: 'gyeonggi-yangpyeong', sido: '경기도', sigungu: '양평군', displayName: '양평군', fullName: '경기도 양평군', latitude: 37.4917, longitude: 127.4876 },
      { id: 'gyeonggi-dongducheon', sido: '경기도', sigungu: '동두천시', displayName: '동두천시', fullName: '경기도 동두천시', latitude: 37.9036, longitude: 127.0607 },
      { id: 'gyeonggi-gapyeong', sido: '경기도', sigungu: '가평군', displayName: '가평군', fullName: '경기도 가평군', latitude: 37.8315, longitude: 127.5095 },
      { id: 'gyeonggi-gwacheon', sido: '경기도', sigungu: '과천시', displayName: '과천시', fullName: '경기도 과천시', latitude: 37.4292, longitude: 126.9876 },
      { id: 'gyeonggi-yeoncheon', sido: '경기도', sigungu: '연천군', displayName: '연천군', fullName: '경기도 연천군', latitude: 38.0964, longitude: 127.0747 },
    ],
  },
  {
    id: 'gangwon',
    name: '강원특별자치도',
    regions: [
      { id: 'gangwon-chuncheon', sido: '강원특별자치도', sigungu: '춘천시', displayName: '춘천시', fullName: '강원특별자치도 춘천시', latitude: 37.8813, longitude: 127.7298 },
      { id: 'gangwon-wonju', sido: '강원특별자치도', sigungu: '원주시', displayName: '원주시', fullName: '강원특별자치도 원주시', latitude: 37.3422, longitude: 127.9202 },
      { id: 'gangwon-gangneung', sido: '강원특별자치도', sigungu: '강릉시', displayName: '강릉시', fullName: '강원특별자치도 강릉시', latitude: 37.7519, longitude: 128.876 },
      { id: 'gangwon-donghae', sido: '강원특별자치도', sigungu: '동해시', displayName: '동해시', fullName: '강원특별자치도 동해시', latitude: 37.5247, longitude: 129.1143 },
      { id: 'gangwon-taebaek', sido: '강원특별자치도', sigungu: '태백시', displayName: '태백시', fullName: '강원특별자치도 태백시', latitude: 37.1652, longitude: 128.9856 },
      { id: 'gangwon-sokcho', sido: '강원특별자치도', sigungu: '속초시', displayName: '속초시', fullName: '강원특별자치도 속초시', latitude: 38.207, longitude: 128.5918 },
      { id: 'gangwon-samcheok', sido: '강원특별자치도', sigungu: '삼척시', displayName: '삼척시', fullName: '강원특별자치도 삼척시', latitude: 37.4498, longitude: 129.1652 },
      { id: 'gangwon-hongcheon', sido: '강원특별자치도', sigungu: '홍천군', displayName: '홍천군', fullName: '강원특별자치도 홍천군', latitude: 37.697, longitude: 127.8887 },
      { id: 'gangwon-yeongwol', sido: '강원특별자치도', sigungu: '영월군', displayName: '영월군', fullName: '강원특별자치도 영월군', latitude: 37.1837, longitude: 128.4619 },
      { id: 'gangwon-pyeongchang', sido: '강원특별자치도', sigungu: '평창군', displayName: '평창군', fullName: '강원특별자치도 평창군', latitude: 37.3708, longitude: 128.3902 },
      { id: 'gangwon-jeongseon', sido: '강원특별자치도', sigungu: '정선군', displayName: '정선군', fullName: '강원특별자치도 정선군', latitude: 37.3806, longitude: 128.6608 },
      { id: 'gangwon-cheorwon', sido: '강원특별자치도', sigungu: '철원군', displayName: '철원군', fullName: '강원특별자치도 철원군', latitude: 38.1468, longitude: 127.3134 },
      { id: 'gangwon-yanggu', sido: '강원특별자치도', sigungu: '양구군', displayName: '양구군', fullName: '강원특별자치도 양구군', latitude: 38.1068, longitude: 127.9893 },
      { id: 'gangwon-inje', sido: '강원특별자치도', sigungu: '인제군', displayName: '인제군', fullName: '강원특별자치도 인제군', latitude: 38.0697, longitude: 128.1704 },
      { id: 'gangwon-goseong', sido: '강원특별자치도', sigungu: '고성군', displayName: '고성군', fullName: '강원특별자치도 고성군', latitude: 38.3806, longitude: 128.4678 },
      { id: 'gangwon-yangyang', sido: '강원특별자치도', sigungu: '양양군', displayName: '양양군', fullName: '강원특별자치도 양양군', latitude: 38.0754, longitude: 128.6189 },
    ],
  },
  {
    id: 'chungbuk',
    name: '충청북도',
    regions: [
      { id: 'chungbuk-cheongju', sido: '충청북도', sigungu: '청주시', displayName: '청주시', fullName: '충청북도 청주시', latitude: 36.6424, longitude: 127.489 },
      { id: 'chungbuk-chungju', sido: '충청북도', sigungu: '충주시', displayName: '충주시', fullName: '충청북도 충주시', latitude: 36.991, longitude: 127.9259 },
      { id: 'chungbuk-jecheon', sido: '충청북도', sigungu: '제천시', displayName: '제천시', fullName: '충청북도 제천시', latitude: 37.1326, longitude: 128.1909 },
      { id: 'chungbuk-boeun', sido: '충청북도', sigungu: '보은군', displayName: '보은군', fullName: '충청북도 보은군', latitude: 36.4895, longitude: 127.7342 },
      { id: 'chungbuk-okcheon', sido: '충청북도', sigungu: '옥천군', displayName: '옥천군', fullName: '충청북도 옥천군', latitude: 36.3015, longitude: 127.5714 },
      { id: 'chungbuk-yeongdong', sido: '충청북도', sigungu: '영동군', displayName: '영동군', fullName: '충청북도 영동군', latitude: 36.175, longitude: 127.7783 },
      { id: 'chungbuk-jincheon', sido: '충청북도', sigungu: '진천군', displayName: '진천군', fullName: '충청북도 진천군', latitude: 36.8554, longitude: 127.4357 },
      { id: 'chungbuk-goesan', sido: '충청북도', sigungu: '괴산군', displayName: '괴산군', fullName: '충청북도 괴산군', latitude: 36.8153, longitude: 127.7869 },
      { id: 'chungbuk-eumseong', sido: '충청북도', sigungu: '음성군', displayName: '음성군', fullName: '충청북도 음성군', latitude: 36.9337, longitude: 127.6908 },
      { id: 'chungbuk-danyang', sido: '충청북도', sigungu: '단양군', displayName: '단양군', fullName: '충청북도 단양군', latitude: 36.9845, longitude: 128.3656 },
    ],
  },
  {
    id: 'chungnam',
    name: '충청남도',
    regions: [
      { id: 'chungnam-cheonan', sido: '충청남도', sigungu: '천안시', displayName: '천안시', fullName: '충청남도 천안시', latitude: 36.8151, longitude: 127.1139 },
      { id: 'chungnam-gongju', sido: '충청남도', sigungu: '공주시', displayName: '공주시', fullName: '충청남도 공주시', latitude: 36.4556, longitude: 127.1246 },
      { id: 'chungnam-boryeong', sido: '충청남도', sigungu: '보령시', displayName: '보령시', fullName: '충청남도 보령시', latitude: 36.3333, longitude: 126.6129 },
      { id: 'chungnam-asan', sido: '충청남도', sigungu: '아산시', displayName: '아산시', fullName: '충청남도 아산시', latitude: 36.7898, longitude: 127.0018 },
      { id: 'chungnam-seosan', sido: '충청남도', sigungu: '서산시', displayName: '서산시', fullName: '충청남도 서산시', latitude: 36.7845, longitude: 126.4503 },
      { id: 'chungnam-nonsan', sido: '충청남도', sigungu: '논산시', displayName: '논산시', fullName: '충청남도 논산시', latitude: 36.1872, longitude: 127.0987 },
      { id: 'chungnam-gyeryong', sido: '충청남도', sigungu: '계룡시', displayName: '계룡시', fullName: '충청남도 계룡시', latitude: 36.2743, longitude: 127.2486 },
      { id: 'chungnam-dangjin', sido: '충청남도', sigungu: '당진시', displayName: '당진시', fullName: '충청남도 당진시', latitude: 36.8898, longitude: 126.6459 },
      { id: 'chungnam-geumsan', sido: '충청남도', sigungu: '금산군', displayName: '금산군', fullName: '충청남도 금산군', latitude: 36.1087, longitude: 127.4883 },
      { id: 'chungnam-buyeo', sido: '충청남도', sigungu: '부여군', displayName: '부여군', fullName: '충청남도 부여군', latitude: 36.2756, longitude: 126.9098 },
      { id: 'chungnam-seocheon', sido: '충청남도', sigungu: '서천군', displayName: '서천군', fullName: '충청남도 서천군', latitude: 36.0805, longitude: 126.6917 },
      { id: 'chungnam-cheongyang', sido: '충청남도', sigungu: '청양군', displayName: '청양군', fullName: '충청남도 청양군', latitude: 36.4594, longitude: 126.8025 },
      { id: 'chungnam-hongseong', sido: '충청남도', sigungu: '홍성군', displayName: '홍성군', fullName: '충청남도 홍성군', latitude: 36.6012, longitude: 126.6608 },
      { id: 'chungnam-yesan', sido: '충청남도', sigungu: '예산군', displayName: '예산군', fullName: '충청남도 예산군', latitude: 36.6811, longitude: 126.8458 },
      { id: 'chungnam-taean', sido: '충청남도', sigungu: '태안군', displayName: '태안군', fullName: '충청남도 태안군', latitude: 36.7456, longitude: 126.2981 },
    ],
  },
  {
    id: 'jeonbuk',
    name: '전북특별자치도',
    regions: [
      { id: 'jeonbuk-jeonju', sido: '전북특별자치도', sigungu: '전주시', displayName: '전주시', fullName: '전북특별자치도 전주시', latitude: 35.8242, longitude: 127.148 },
      { id: 'jeonbuk-gunsan', sido: '전북특별자치도', sigungu: '군산시', displayName: '군산시', fullName: '전북특별자치도 군산시', latitude: 35.9676, longitude: 126.7368 },
      { id: 'jeonbuk-iksan', sido: '전북특별자치도', sigungu: '익산시', displayName: '익산시', fullName: '전북특별자치도 익산시', latitude: 35.9483, longitude: 126.9578 },
      { id: 'jeonbuk-jeongeup', sido: '전북특별자치도', sigungu: '정읍시', displayName: '정읍시', fullName: '전북특별자치도 정읍시', latitude: 35.5699, longitude: 126.8577 },
      { id: 'jeonbuk-namwon', sido: '전북특별자치도', sigungu: '남원시', displayName: '남원시', fullName: '전북특별자치도 남원시', latitude: 35.4164, longitude: 127.3904 },
      { id: 'jeonbuk-gimje', sido: '전북특별자치도', sigungu: '김제시', displayName: '김제시', fullName: '전북특별자치도 김제시', latitude: 35.8036, longitude: 126.8808 },
      { id: 'jeonbuk-wanju', sido: '전북특별자치도', sigungu: '완주군', displayName: '완주군', fullName: '전북특별자치도 완주군', latitude: 35.9046, longitude: 127.1648 },
      { id: 'jeonbuk-muju', sido: '전북특별자치도', sigungu: '무주군', displayName: '무주군', fullName: '전북특별자치도 무주군', latitude: 36.0068, longitude: 127.6607 },
      { id: 'jeonbuk-buan', sido: '전북특별자치도', sigungu: '부안군', displayName: '부안군', fullName: '전북특별자치도 부안군', latitude: 35.7317, longitude: 126.7332 },
    ],
  },
  {
    id: 'jeonnam-gwangju',
    name: '전남광주통합특별시',
    regions: [
      // 기존 광주광역시 5개 자치구 -> 전남광주통합특별시 소속
      { id: 'jeonnam-gwangju-dong', sido: '전남광주통합특별시', sigungu: '동구', displayName: '동구', fullName: '전남광주통합특별시 동구', latitude: 35.146, longitude: 126.9234 },
      { id: 'jeonnam-gwangju-seo', sido: '전남광주통합특별시', sigungu: '서구', displayName: '서구', fullName: '전남광주통합특별시 서구', latitude: 35.152, longitude: 126.89 },
      { id: 'jeonnam-gwangju-nam', sido: '전남광주통합특별시', sigungu: '남구', displayName: '남구', fullName: '전남광주통합특별시 남구', latitude: 35.1329, longitude: 126.9025 },
      { id: 'jeonnam-gwangju-buk', sido: '전남광주통합특별시', sigungu: '북구', displayName: '북구', fullName: '전남광주통합특별시 북구', latitude: 35.1743, longitude: 126.9122 },
      { id: 'jeonnam-gwangju-gwangsan', sido: '전남광주통합특별시', sigungu: '광산구', displayName: '광산구', fullName: '전남광주통합특별시 광산구', latitude: 35.1395, longitude: 126.7937 },

      // 기존 전라남도 22개 시·군 -> 전남광주통합특별시 소속
      { id: 'jeonnam-gwangju-mokpo', sido: '전남광주통합특별시', sigungu: '목포시', displayName: '목포시', fullName: '전남광주통합특별시 목포시', latitude: 34.8118, longitude: 126.3922 },
      { id: 'jeonnam-gwangju-yeosu', sido: '전남광주통합특별시', sigungu: '여수시', displayName: '여수시', fullName: '전남광주통합특별시 여수시', latitude: 34.7604, longitude: 127.6622 },
      { id: 'jeonnam-gwangju-suncheon', sido: '전남광주통합특별시', sigungu: '순천시', displayName: '순천시', fullName: '전남광주통합특별시 순천시', latitude: 34.9506, longitude: 127.4872 },
      { id: 'jeonnam-gwangju-naju', sido: '전남광주통합특별시', sigungu: '나주시', displayName: '나주시', fullName: '전남광주통합특별시 나주시', latitude: 35.0159, longitude: 126.7108 },
      { id: 'jeonnam-gwangju-gwangyang', sido: '전남광주통합특별시', sigungu: '광양시', displayName: '광양시', fullName: '전남광주통합특별시 광양시', latitude: 34.9407, longitude: 127.6959 },
      { id: 'jeonnam-gwangju-damyang', sido: '전남광주통합특별시', sigungu: '담양군', displayName: '담양군', fullName: '전남광주통합특별시 담양군', latitude: 35.3212, longitude: 126.9882 },
      { id: 'jeonnam-gwangju-gokseong', sido: '전남광주통합특별시', sigungu: '곡성군', displayName: '곡성군', fullName: '전남광주통합특별시 곡성군', latitude: 35.2818, longitude: 127.2917 },
      { id: 'jeonnam-gwangju-gurye', sido: '전남광주통합특별시', sigungu: '구례군', displayName: '구례군', fullName: '전남광주통합특별시 구례군', latitude: 35.2025, longitude: 127.4628 },
      { id: 'jeonnam-gwangju-goheung', sido: '전남광주통합특별시', sigungu: '고흥군', displayName: '고흥군', fullName: '전남광주통합특별시 고흥군', latitude: 34.6111, longitude: 127.2858 },
      { id: 'jeonnam-gwangju-boseong', sido: '전남광주통합특별시', sigungu: '보성군', displayName: '보성군', fullName: '전남광주통합특별시 보성군', latitude: 34.7714, longitude: 127.0798 },
      { id: 'jeonnam-gwangju-hwasun', sido: '전남광주통합특별시', sigungu: '화순군', displayName: '화순군', fullName: '전남광주통합특별시 화순군', latitude: 35.0645, longitude: 126.9865 },
      { id: 'jeonnam-gwangju-jangheung', sido: '전남광주통합특별시', sigungu: '장흥군', displayName: '장흥군', fullName: '전남광주통합특별시 장흥군', latitude: 34.6817, longitude: 126.9069 },
      { id: 'jeonnam-gwangju-gangjin', sido: '전남광주통합특별시', sigungu: '강진군', displayName: '강진군', fullName: '전남광주통합특별시 강진군', latitude: 34.642, longitude: 126.7675 },
      { id: 'jeonnam-gwangju-haenam', sido: '전남광주통합특별시', sigungu: '해남군', displayName: '해남군', fullName: '전남광주통합특별시 해남군', latitude: 34.5735, longitude: 126.5989 },
      { id: 'jeonnam-gwangju-yeongam', sido: '전남광주통합특별시', sigungu: '영암군', displayName: '영암군', fullName: '전남광주통합특별시 영암군', latitude: 34.8001, longitude: 126.6968 },
      { id: 'jeonnam-gwangju-muan', sido: '전남광주통합특별시', sigungu: '무안군', displayName: '무안군', fullName: '전남광주통합특별시 무안군', latitude: 34.9904, longitude: 126.4817 },
      { id: 'jeonnam-gwangju-hampyeong', sido: '전남광주통합특별시', sigungu: '함평군', displayName: '함평군', fullName: '전남광주통합특별시 함평군', latitude: 35.0657, longitude: 126.5162 },
      { id: 'jeonnam-gwangju-yeonggwang', sido: '전남광주통합특별시', sigungu: '영광군', displayName: '영광군', fullName: '전남광주통합특별시 영광군', latitude: 35.2774, longitude: 126.5121 },
      { id: 'jeonnam-gwangju-jangseong', sido: '전남광주통합특별시', sigungu: '장성군', displayName: '장성군', fullName: '전남광주통합특별시 장성군', latitude: 35.3018, longitude: 126.7847 },
      { id: 'jeonnam-gwangju-wando', sido: '전남광주통합특별시', sigungu: '완도군', displayName: '완도군', fullName: '전남광주통합특별시 완도군', latitude: 34.311, longitude: 126.755 },
      { id: 'jeonnam-gwangju-jindo', sido: '전남광주통합특별시', sigungu: '진도군', displayName: '진도군', fullName: '전남광주통합특별시 진도군', latitude: 34.4868, longitude: 126.2634 },
      { id: 'jeonnam-gwangju-sinan', sido: '전남광주통합특별시', sigungu: '신안군', displayName: '신안군', fullName: '전남광주통합특별시 신안군', latitude: 34.8262, longitude: 126.1077 },
    ],
  },
  {
    id: 'gyeongbuk',
    name: '경상북도',
    regions: [
      { id: 'gyeongbuk-pohang', sido: '경상북도', sigungu: '포항시', displayName: '포항시', fullName: '경상북도 포항시', latitude: 36.019, longitude: 129.3435 },
      { id: 'gyeongbuk-gyeongju', sido: '경상북도', sigungu: '경주시', displayName: '경주시', fullName: '경상북도 경주시', latitude: 35.8562, longitude: 129.2247 },
      { id: 'gyeongbuk-gimcheon', sido: '경상북도', sigungu: '김천시', displayName: '김천시', fullName: '경상북도 김천시', latitude: 36.1398, longitude: 128.1136 },
      { id: 'gyeongbuk-andong', sido: '경상북도', sigungu: '안동시', displayName: '안동시', fullName: '경상북도 안동시', latitude: 36.5684, longitude: 128.7294 },
      { id: 'gyeongbuk-gumi', sido: '경상북도', sigungu: '구미시', displayName: '구미시', fullName: '경상북도 구미시', latitude: 36.1195, longitude: 128.3443 },
      { id: 'gyeongbuk-yeongju', sido: '경상북도', sigungu: '영주시', displayName: '영주시', fullName: '경상북도 영주시', latitude: 36.8057, longitude: 128.6241 },
      { id: 'gyeongbuk-yeongcheon', sido: '경상북도', sigungu: '영천시', displayName: '영천시', fullName: '경상북도 영천시', latitude: 35.9733, longitude: 128.9386 },
      { id: 'gyeongbuk-sangju', sido: '경상북도', sigungu: '상주시', displayName: '상주시', fullName: '경상북도 상주시', latitude: 36.4109, longitude: 128.1591 },
      { id: 'gyeongbuk-gyeongsan', sido: '경상북도', sigungu: '경산시', displayName: '경산시', fullName: '경상북도 경산시', latitude: 35.8251, longitude: 128.7413 },
      { id: 'gyeongbuk-chilgok', sido: '경상북도', sigungu: '칠곡군', displayName: '칠곡군', fullName: '경상북도 칠곡군', latitude: 35.9956, longitude: 128.4016 },
      { id: 'gyeongbuk-ulleung', sido: '경상북도', sigungu: '울릉군', displayName: '울릉군', fullName: '경상북도 울릉군', latitude: 37.4844, longitude: 130.9056 },
    ],
  },
  {
    id: 'gyeongnam',
    name: '경상남도',
    regions: [
      { id: 'gyeongnam-changwon', sido: '경상남도', sigungu: '창원시', displayName: '창원시', fullName: '경상남도 창원시', latitude: 35.228, longitude: 128.6811 },
      { id: 'gyeongnam-jinju', sido: '경상남도', sigungu: '진주시', displayName: '진주시', fullName: '경상남도 진주시', latitude: 35.1802, longitude: 128.1076 },
      { id: 'gyeongnam-tongyeong', sido: '경상남도', sigungu: '통영시', displayName: '통영시', fullName: '경상남도 통영시', latitude: 34.8544, longitude: 128.4332 },
      { id: 'gyeongnam-sacheon', sido: '경상남도', sigungu: '사천시', displayName: '사천시', fullName: '경상남도 사천시', latitude: 35.0037, longitude: 128.0642 },
      { id: 'gyeongnam-gimhae', sido: '경상남도', sigungu: '김해시', displayName: '김해시', fullName: '경상남도 김해시', latitude: 35.2335, longitude: 128.881 },
      { id: 'gyeongnam-miryang', sido: '경상남도', sigungu: '밀양시', displayName: '밀양시', fullName: '경상남도 밀양시', latitude: 35.5038, longitude: 128.7466 },
      { id: 'gyeongnam-geoje', sido: '경상남도', sigungu: '거제시', displayName: '거제시', fullName: '경상남도 거제시', latitude: 34.8806, longitude: 128.6211 },
      { id: 'gyeongnam-yangsan', sido: '경상남도', sigungu: '양산시', displayName: '양산시', fullName: '경상남도 양산시', latitude: 35.335, longitude: 129.0374 },
      { id: 'gyeongnam-namhae', sido: '경상남도', sigungu: '남해군', displayName: '남해군', fullName: '경상남도 남해군', latitude: 34.8377, longitude: 127.8924 },
    ],
  },
  {
    id: 'jeju',
    name: '제주특별자치도',
    regions: [
      { id: 'jeju-jeju', sido: '제주특별자치도', sigungu: '제주시', displayName: '제주시', fullName: '제주특별자치도 제주시', latitude: 33.4996, longitude: 126.5312 },
      { id: 'jeju-seogwipo', sido: '제주특별자치도', sigungu: '서귀포시', displayName: '서귀포시', fullName: '제주특별자치도 서귀포시', latitude: 33.2541, longitude: 126.5601 },
    ],
  },
];

/**
 * 전국 전체 시·군·구 행정구역 평탄화 배열
 */
export const ALL_REGIONS: Region[] = PROVINCES.flatMap((p) => p.regions);
